### ISSUE TITLE
역할분담

### ISSUE THREAD

**Issue by Kim-kanghyun** [Kim-kanghyun/Team_project#7]
역할분담 논의합시다

**Comment by rladp127** [comment]
지금 crud, 검색 (이름 대여차종 시간), 파일 로드 및 저장, wiki 페이지 작성, 가격 계산 함수

**Comment by rladp127** [comment]
이렇게 되어있는 거 맞을까요?

**Comment by rladp127** [comment]
총 역할이요!

**Comment by Kim-kanghyun** [comment]
넵

> 지금 crud, 검색 (이름 대여차종 시간), 파일 로드 및 저장, wiki 페이지 작성, 가격 계산 함수

넵 맞습니다!

**Comment by Kim-kanghyun** [comment]
아 저기에 시간 계산함수도 있어요!!

**Comment by rladp127** [comment]
crud, 검색 (이름 대여차종 시간), 파일 로드 및 저장, wiki 페이지 작성, 가격 계산 함수, 시간 계산 함수 에서 역할 다시 나누면 될 것 같은데
제가 검색 부분 담당하고 또 어떤 거 담당하면 될까요?

**Comment by rladp127** [comment]
혹시 아까 마크다운 말씀하셨던 거 같은데 필요하시면 제가 wiki page 담당해도 괜찮습니다!

**Comment by Kim-kanghyun** [comment]
일단 create랑 update는 사실상 함수내용이 거의 같아서 한사람이 맡는게 좋을것 같구요!!

**Comment by rladp127** [comment]
네네

**Comment by KimSeongKyung** [comment]
그러면 검색 3개랑함수랑 위키 담당하실래요??

**Comment by Kim-kanghyun** [comment]
아니면 제가 위키 담당해도 됩니다!!

**Comment by rladp127** [comment]
네 저는 괜찮습니다

**Comment by rladp127** [comment]
그 제가 검색만 하면 분량이 너무 적어질 것 같아서 ㅠㅠ 각자 역할 중에서 조금 나눠서 주셔도 돼요.!

**Comment by KimSeongKyung** [comment]
제가 RD랑 파일 입출력 담당하고
강현학우님이 CU랑 대여시간 계산하면

**Comment by KimSeongKyung** [comment]
아 가격계산은 누가 하죠??

**Comment by Kim-kanghyun** [comment]
아 그러면 제가 하겠습니다!!

**Comment by KimSeongKyung** [comment]
넵 감사합니다!!

**Comment by KimSeongKyung** [comment]
> 그 제가 검색만 하면 분량이 너무 적어질 것 같아서 ㅠㅠ 각자 역할 중에서 조금 나눠서 주셔도 돼요.!

저희도 함수 네개밖에 안해서 ㅋㅋ 위키까지 담당하시면 딱 될 것 같아요!!

**Comment by Kim-kanghyun** [comment]
맞아요!!

**Comment by rladp127** [comment]
아 그러면 강현학우님 위키페이지 담당을 제가 해도 괜찮을까요??

**Comment by Kim-kanghyun** [comment]
넵 그래주시면 감사하겠습니다!!

**Comment by rladp127** [comment]
아 네네! 알겠습니다

**Comment by KimSeongKyung** [comment]
그려면 
강현 - CU, 대여시간 계산, 가격 계산
성경 - RD, 파일 입출력
예인 - 검색3개, 위키

**Comment by KimSeongKyung** [comment]
이렇게 하면 되나요??

**Comment by Kim-kanghyun** [comment]
오 딱 균형맞고 좋네요!!

**Comment by KimSeongKyung** [comment]
굳~~

**Comment by rladp127** [comment]
네네! 👍👍

**Comment by KimSeongKyung** [comment]
넵~!!!

**Comment by KimSeongKyung** [comment]
저희 언제까지 구현해서 올리는 걸로 할까요??

**Comment by Kim-kanghyun** [comment]
그러면 이렇게 역할 분담한거 위키에 예인학우님께서 바꿔서 올려주시면 감사하겠습니다!

**Comment by rladp127** [comment]
네네! 포항 도착하는 대로 변경 해놓겠습니다

**Comment by rladp127** [comment]
> 저희 언제까지 구현해서 올리는 걸로 할까요??

언제까지 가능하세요?.?

**Comment by Kim-kanghyun** [comment]
음... 일단 내일까지니깐.... 제가 헤더파일 지금 바로 올리고 각각 manager.c나 car.c carmain.c에 올리는것은 내일 정오까지 하는걸로!

**Comment by Kim-kanghyun** [comment]
물론 빠르면 빠를수록 더 좋습니다!!

**Comment by KimSeongKyung** [comment]
넵!! 내일 정오 전까지 pr 보낼게요!

**Comment by Kim-kanghyun** [comment]
아 pr안보내도 아마 push 될겁니다!!

**Comment by Kim-kanghyun** [comment]
잘 모르겠네요 암튼 그떄까지 하는걸로 하죠!!

**Comment by KimSeongKyung** [comment]
엇,,!! 근데 평가기준에 
협업 평가

mini project의 설계 및 그에 따른 전체적인 완성도 평가

Repository PR과 소유자 PR Merge내역

이렇게 되어있더라구요!

**Comment by rladp127** [comment]
아 collaborator 작업이라 가능한가보네요!! 저도 내일정오까지 완성하겠습니다~!!

**Comment by rladp127** [comment]
> 엇,,!! 근데 평가기준에 협업 평가
> 
> mini project의 설계 및 그에 따른 전체적인 완성도 평가
> 
> Repository PR과 소유자 PR Merge내역
> 
> 이렇게 되어있더라구요!

아 저번에 ta님 답변에 괜찮다고 왔다고 하셔서 방식은 상관 없을 줄 알았는데.. 아니면 티에이님께 그 부분도 여쭤 볼까요 ㅠㅠ

**Comment by KimSeongKyung** [comment]
그러게요 ㅠㅠ  저도 이부분은 방금 확인해서..
넵 그래주시면 감사하겠습니다.!!

**Comment by rladp127** [comment]
지금 메일을 보실지 모르겠는데 한 번 여쭤볼게요!

**Comment by KimSeongKyung** [comment]
네! 감사합니다 답장 오면 연락주세요:)

**Comment by KimSeongKyung** [comment]
저희 더 얘기할 게 있을까요??

**Comment by Kim-kanghyun** [comment]
음... 이정도면 충분할 것 같네요!!

**Comment by rladp127** [comment]
전 이제 괜찮을 것 같아요!

**Comment by rladp127** [comment]
네네!

**Comment by KimSeongKyung** [comment]
네 수고하셨습니당~~

**Comment by Kim-kanghyun** [comment]
수고하셨습니다!!
